mastermind/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog

urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),] + (
    i18n_patterns(
        path('', include('mastermind.users.urls', namespace="users")),
        path('game/', include('mastermind.game.urls', namespace="game")),
        path("rules/", TemplateView.as_view(template_name='pages/rules.html'), name="rules"),
        path("terms/", TemplateView.as_view(template_name='pages/terms.html'), name="terms"),
        path('admin/', admin.site.urls),
        path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
        prefix_default_language=True
    ) 
)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += [
    #     path(
    #         "400/",
    #         default_views.bad_request,
    #         kwargs={"exception": Exception("Bad Request!")},
    #     ),
    #     path(
    #         "403/",
    #         default_views.permission_denied,
    #         kwargs={"exception": Exception("Permission Denied")},
    #     ),
    #     path(
    #         "404/",
    #         default_views.page_not_found,
    #         kwargs={"exception": Exception("Page not Found")},
    #     ),
    #     path("500/", default_views.server_error),
    # ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mastermind/users/templatetags/urls.py
from typing import Any, Optional, Dict

from django import template, urls

register = template.Library()


@register.simple_tag(takes_context=True)
def translate_url(context: Dict[str, Any], language: Optional[str]) -> str:
    """Get the absolute URL of the current page for the specified language.

    Usage:
        {% translate_url 'en' %}
    """
    url = context['request'].build_absolute_uri()
    return urls.translate_url(url, language)

mastermind/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from mastermind.users import views

app_name = 'users'

urlpatterns = [
    path("", views.login_view, name="index"),
    path('signup/', views.signup_view, name='signup'),
    path('account/', views.account, name='account'),
    path('delete-account/', views.delete_account, name='delete_account'),
    path("signup/<uuid:token>/", views.signup_view, name="signup"),
    path('activate/<uidb64>/<token>/', views.activate_user, name='activate'),
    # django.contrib.auth views
    path('signin/', views.login_view, name='signin'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="users/registration/password_reset_done.html"), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="users/registration/password_reset_complete.html"), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mastermind/users/forms.py
import datetime
from crispy_forms.bootstrap import AppendedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.db import models
from django.utils import timezone
from django.utils.functional import lazy
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from mastermind.users.utils import resize_square
from PIL import Image

User = get_user_model()
mark_safe_lazy = lazy(mark_safe, str)


class LoginForm(auth_forms.AuthenticationForm):
# class LoginForm(forms.Form):
    """ Simple form for login """
    email = forms.EmailField(
        label="Email",
        widget=forms.TextInput(attrs={'placeholder': _('Email*')}))
    password = forms.CharField(label=_("Password*"),
        widget=forms.PasswordInput(attrs={'placeholder': _('Password*')}))
    stay_connected = forms.BooleanField(label=_("Remember me"), required=False)

    def __init__(self, *args, **kwargs):
        """ Init styles necessary for crispy form """
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.fields['email'].label = False
        self.fields['password'].label = False



class UserChangeForm(auth_forms.UserChangeForm):
    """ form for user change in admin """
    class Meta(auth_forms.UserChangeForm.Meta):
        model = User
        fields = ['email', 'password', 'language']


#####################################################
#                   USERCREATION                    #
#####################################################
class UserCreationForm(auth_forms.UserCreationForm):
    """ Form for signin without username and with CGU acceptation """
    # username = None
    email = models.EmailField(
        unique=True, max_length=255, blank=False,)
    password1 = forms.CharField(label=_("Password*"),
        widget=forms.PasswordInput(attrs={'placeholder': _('Password*')}))
    accept_terms = mark_safe_lazy(
        _('I have red and accept the <a href="/terms">Terms</a> to subscribe.'))
    cgu_check = forms.BooleanField(
        label=_("Terms"),
        required=True,
        help_text=accept_terms
    )

    def __init__(self, *args, **kwargs):
        """ Init styles necessary for crispy form """
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.fields['username'].widget.attrs['placeholder'] = _('Nickname*')
        self.fields['username'].label = False
        self.fields['email'].widget.attrs['placeholder'] = _('Email*')
        self.fields['email'].label = False
        self.fields['password1'].label = False
        self.fields['password2'].label = False
        self.fields['password2'].widget.attrs['placeholder'] = _('Confirm password*')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'cgu_check')
        help_texts = {'password1': None,}

    def clean_email(self):
        """ Check if already used email """
        email = self.cleaned_data["email"]
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        self.add_error('email', _("This email address is already used"))
        return email


#####################################################
#                   USERUPDATE                      #
#####################################################
class UserUpdateForm(forms.ModelForm):
    """ Let user update his own informations """
    error_messages = auth_forms.UserCreationForm.error_messages.update(
        {"duplicate_email": _("This email address is already used")}
    )
    delete_avatar = forms.BooleanField(label=_("Delete my profile picture"), required=False)

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'language',
            'avatar',
            'delete_avatar',
            )
        widgets = {'avatar': forms.FileInput()}

    def __init__(self, *args, **kwargs):
        """ Init styles """
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.attrs['autocomplete'] = 'off'
        self.helper.form_tag = False

    def clean_email(self):
        """ Check if email not already in use by other user """
        email = self.cleaned_data.get('email')
        if 'email' in self.changed_data:
            try:
                User.objects.get(email=email)
            except User.DoesNotExist:
                return email
            self.add_error('email', _("This email address is already used"))
        return email

    def clean_avatar(self):
        """
        Crop and resize avatar to 150px
        Validation could be made by validators
        but useful in clean before saving it
        """
        avatar = self.cleaned_data.get('avatar')
        if avatar and 'avatar' in self.changed_data:
            image = Image.open(avatar)
            # validate content type
            if image.format not in ['PNG', 'JPEG', 'GIF']:
                self.add_error('avatar', _("Image format must be JPEG, GIF ou PNG."))
            # validate file size
            if len(avatar) > (1000 * 1024):
                self.add_error('avatar', _("Image size must be lower than 1Mo."))
            avatar = resize_square(avatar, 'avatar')
        return avatar

    def save(self, commit=True):
        """
        Not necessary to check if username is not taken
        since it's done in the clean_email method
        """
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance
  

#####################################################
#                   AVATARFORM                      #
#####################################################
class AvatarUpdateForm(forms.ModelForm):
    """
    Update an avatar via this form
    Uses an ajax request to /users/avatar
    """
    class Meta:
        model = User
        fields = ('avatar',)
        widgets = {
            'avatar': forms.FileInput(
                attrs={
                    'action': '/users/avatar',
                    'id': "form_avatar_file"}
            )}

mastermind/users/views.py
import os
from os import remove

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.translation import LANGUAGE_SESSION_KEY, activate
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST
from django.views.i18n import translate_url

from mastermind.users.forms import (AvatarUpdateForm, LoginForm,
                                    UserCreationForm, UserUpdateForm)

User = get_user_model()

#####################################################
#                   REGISTRATION                    #
#####################################################
def login_view(request):
    """ Custom view for logging in using email """
    form = LoginForm(request.POST if request.method == 'POST' else None)
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            if user.last_login:
                request.session['last_login'] = user.last_login.timestamp()
            if user.is_active:
                language = user.language
                login(request, user)
                if request.POST.get('stay_connected', False):
                    request.session.set_expiry(600)
                else:
                    request.session.set_expiry(0)
                request.session[LANGUAGE_SESSION_KEY] = language
                next = request.GET.get('next')
                return redirect('game:new_game') if not next else redirect(next)
        else:
            messages.error(request, _("Invalid email or password"))
    title = _("Sign in")
    return render(request, 'users/registration/login.html', {'title': title, 'form': form, 'rules': True})


def signup_view(request):
    """ Custom view for creating a user """
    form = UserCreationForm(request.POST if request.method == 'POST' else None)
    if request.method == 'GET':
        return render(request, 'users/registration/signup.html', locals())

    if request.method == 'POST':
        if not form.is_valid():
            return render(request, 'users/registration/signup.html', locals())
        email = form.cleaned_data.get('email')
        # Create user
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # Send email for activation
        mail_subject = _("Confirm your email address")
        message = render_to_string(
            'users/registration/signup_validation_email.html',
            {
                'site': f'https://{get_current_site(request).domain}',
                'user': user,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
        EmailMessage(mail_subject,message,from_email="contact@mastermind.ovh",to=[email]).send()
        return render(request, 'users/registration/signup_validation_begin.html')


def activate_user(request, uidb64, token):
    """
    Check token fit to user and decode uid
    Activate user if those are OK
    """
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, 'users/registration/signup_validation_end.html')
    else:
        return render(request, 'users/registration/signup_validation_error.html')


class PasswordResetView(auth_views.PasswordResetView):
    template_name = "users/registration/password_reset_form.html"
    email_template_name = "users/registration/password_reset_email.html"
    subject_template_name = "users/registration/password_reset_subject.txt"
    success_url = reverse_lazy('users:password_reset_done')


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = "users/registration/password_reset_confirm.html"
    success_url = reverse_lazy('users:password_reset_complete')


class PasswordChangeView(auth_views.PasswordChangeView):
    template_name='users/user_password_change.html'


#####################################################
#                   USER UPDATE                     #
#####################################################
@login_required
def account(request):
    """ Render form to update datas of user and avatar """
    form = UserUpdateForm(instance=request.user)
    languages = settings.LANGUAGES
    title = _("Account")
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            user = form.save()
            avatar = form.cleaned_data.get('avatar', None)
            if avatar:
                request.user.avatar.save('avatar.jpeg', avatar, save=True)
            url = translate_url(reverse('users:account'), user.language)
            activate(user.language)
            if hasattr(request, 'session'):
                request.session[LANGUAGE_SESSION_KEY] = user.language
            if request.POST.get('delete_avatar'):
                user.avatar.delete()   #  <--- Efface le fichier
            messages.success(request, _("Information saved"))
            form = UserUpdateForm(instance=user)
            return redirect(url)
        return  render(request, 'users/user_account.html', locals())

    return render(request, 'users/user_account.html', locals())

@login_required
def delete_account(request):
    """ Permanently delete an account """
    if request.method == 'POST':
        request.user.delete()
        logout(request)
        return  redirect(reverse('users:index'))

    return render(request, 'users/user_delete.html')

mastermind/users/templates/users/user_account.html
{% extends 'app_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}

  <div class="row">
    <div class="col-xl-7 col-lg-6 mx-auto my-auto">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary"> {% translate "Profile" %}</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v fa-sm fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink" style="">
              {% comment %} <div class="dropdown-header">Dropdown Header:</div> {% endcomment %}
              <a class="dropdown-item" href="{% url 'users:password_change' %}">{% translate "Change Password" %}</a>
              <a class="dropdown-item" href="{% url 'users:delete_account' %}">{% translate "Delete account" %}</a>
              {% comment %} <div class="dropdown-divider"></div> {% endcomment %}
            </div>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <img class="avatar" src="{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'users/img/avatar.png' %}{% endif %}" id="user_avatar" alt="{{ user.username }}">
            </div>
            <div class="col-md-8">
              <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% crispy form %}
                <button type="submit" name="action" value="save" class="float-right btn-md btn btn-primary"><i class="fas fa-save"></i> {% translate "Save" %}</button>
              </form>
              
              {% comment %} {% for lang_code, lang_name in languages %}
                  {% language lang_code %}
                      <li>
                      <i class="icon-wrench"></i>
                          <a href="/{{ lang_code }}/"
                              {% if lang_code == LANGUAGE_CODE %}
                              {% endif %}>
                          {% if lang_code == 'en' %}
                          <img src="{% static "img/en.png" %}" alt="Eng"
                                style="height: 13pt;
                                margin-bottom: 3pt;">
                              {{ lang_code|upper }}
                          {% endif %}
                          {% if lang_code == 'id' %}
                          <img src="{% static "img/id.png" %}" alt="Ind"
                                style="height: 13pt;
                                margin-bottom: 3pt;">
                              {{ lang_code|upper }}
                          {% endif %}

                      </a>
                      </li>
                  {% endlanguage %}
              {% endfor %} {% endcomment %}


            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

{% endblock content %}

mastermind/users/templates/users/user_delete.html
{% extends 'app_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}

  <div class="row">
    <!-- Area Chart -->
    <div class="col-xl-7 col-lg-6 mx-auto my-auto">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary"> {% translate "Delete account" %}</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v fa-sm fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink" style="">
              {% comment %} <div class="dropdown-header">Dropdown Header:</div> {% endcomment %}
              <a class="dropdown-item" href="{% url 'users:password_change' %}">{% translate "Change Password" %}</a>
              <a class="dropdown-item" href="{% url 'users:account' %}">{% translate "Profile" %}</a>
              {% comment %} <div class="dropdown-divider"></div> {% endcomment %}
            </div>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">

        <p>{% translate "Are you sure you want to delete your account ?" %}</p>
        <p>{% translate "You won't be able to access the site unless you recreate an account. <b>All your data will be lost</b>!" %}</p>
      
              <form method="POST" enctype="multipart/form-data" class="text-right">
              {% csrf_token %}
                <a href="{% url 'users:account' %}" class="btn-md btn btn-primary">{% translate "No" %}</a>
                <button type="submit" name="action" value="save" class="btn-md btn btn-danger">{% translate "Yes" %}</button>
              </form>
        </div>
      </div>
    </div>

  </div>

{% endblock content %}

mastermind/users/templates/users/user_password_change.html
{% extends 'app_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}

  <div class="row">
    <!-- Area Chart -->
    <div class="col-xl-7 col-lg-6 mx-auto my-auto">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary"> {% translate "Password change" %}</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v fa-sm fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink" style="">
              {% comment %} <div class="dropdown-header">Dropdown Header:</div> {% endcomment %}
              <a class="dropdown-item" href="{% url 'users:account' %}">{% translate "Profile" %}</a>
              <a class="dropdown-item" href="{% url 'users:delete_account' %}">{% translate "Delete account" %}</a>
              {% comment %} <div class="dropdown-divider"></div> {% endcomment %}
            </div>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
      
              <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {{ field|as_crispy_field }}
                {% endfor %}
                <button type="submit" name="action" value="save" class="float-right btn-md btn btn-primary"><i class="fas fa-save"></i> {% translate "Save" %}</button>
              </form>
        </div>
      </div>
    </div>

  </div>

{% endblock content %}