mastermind/game/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from mastermind.game import views

app_name = 'game'

urlpatterns = [
    path("", TemplateView.as_view(template_name='game/index.html'), name="index"),
    path("<int:game_id>/", views.game, name="detail"),
    path("<int:game_id>/giveup/", views.giveup, name="giveup"),
    path("new/", views.new_game, name="new_game"),
    path("ranking/", views.ranking, name="ranking"),
    path("my-games/", views.user_games, name="user_games"),
    path("new/<str:go>/", views.new_game, name="new_game"),
    path("<int:game_id>/guess/", views.guess, name="guess"),
    path("<int:game_id>/delete/", views.delete, name="delete"),
]

mastermind/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog

urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),] + (
    i18n_patterns(
        path('', include('mastermind.users.urls', namespace="users")),
        path('game/', include('mastermind.game.urls', namespace="game")),
        path("rules/", TemplateView.as_view(template_name='pages/rules.html'), name="rules"),
        path("terms/", TemplateView.as_view(template_name='pages/terms.html'), name="terms"),
        path('admin/', admin.site.urls),
        path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
        prefix_default_language=True
    ) 
)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += [
    #     path(
    #         "400/",
    #         default_views.bad_request,
    #         kwargs={"exception": Exception("Bad Request!")},
    #     ),
    #     path(
    #         "403/",
    #         default_views.permission_denied,
    #         kwargs={"exception": Exception("Permission Denied")},
    #     ),
    #     path(
    #         "404/",
    #         default_views.page_not_found,
    #         kwargs={"exception": Exception("Page not Found")},
    #     ),
    #     path("500/", default_views.server_error),
    # ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mastermind/game/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import get_supported_language_variant
from django.utils.translation import gettext as _

from .utils import solution_init

User = get_user_model()


class Game(models.Model):

    date_begin = models.DateTimeField(
        _("Begining of game"), auto_now_add=True)
    date_end = models.DateTimeField(
        _("End of game"), null=True)
    solution = models.CharField(
        _("Solution"), max_length=4, default=solution_init)
    win = models.BooleanField(
        "Win", default=False)
    player = models.ForeignKey(
        User, related_name="games", on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date_end']
        default_permissions = ()
        permissions = (
            ('view_stats', _('Can play')),
        )

    @property
    def duration(self):
        if self.date_end:
            return  self.date_end - self.date_begin
        return None

    @property
    def peg1(self):
        return self.solution[0]

    @property
    def peg2(self):
        return self.solution[1]

    @property
    def peg3(self):
        return self.solution[2]

    @property
    def peg4(self):
        return self.solution[3]

    def get_absolute_url(self):
        """Get url for game detail view"""
        return reverse("game:detail", kwargs={"game_id": self.id})


class Guess(models.Model):
    date_played = models.DateTimeField(
        _("Played on the"), auto_now_add=True)
    combination = models.CharField(
        _("Combination"), max_length=4, blank=False)
    game = models.ForeignKey(
        _('Game'), related_name="guesses", on_delete=models.CASCADE, null=False)
    num = models.PositiveIntegerField(
        _("Number"), default=1
    )

    @property
    def color1(self):
        return self.combination[0]

    @property
    def color2(self):
        return self.combination[1]

    @property
    def color3(self):
        return self.combination[2]

    @property
    def color4(self):
        return self.combination[3]

    @property
    def result(self): 
        good_place, wrong_place = 0, 0
        solution = list(self.game.solution)
        combination = list(self.combination)
        # first list all good pegs
        # game.solution = '1141', result('1111') must be 3, 0 but not 3, 1
        for i in range(len(combination)):
            if combination[i] == solution[i]:
                good_place += 1
                # assign 2 different char to solution and combination
                solution[i] = '-'
                combination[i] = '%'
        for item in combination:
            if item in solution:
                wrong_place += 1
                to_remove = solution.index(item)
                solution[to_remove] = '-'
        return {'good_place': good_place, 'wrong_place': wrong_place, 'gameover': False}


    def save(self, *args, **kwargs):
        num_max_guess = 4
        try:
            last_guess = self.game.guesses.all()[0]
            self.num = last_guess.num + 1
        except IndexError:
            self.num = 1
        if self.num == settings.ROUND_NUMBER:
            self.game.date_end = timezone.now()
            self.game.save()
        elif self.num > settings.ROUND_NUMBER or self.game.win:
            raise ValidationError('La partie est finie')
        elif len(self.combination) != 4:
            raise ValidationError('Guess can not be empty')
        if self.combination == self.game.solution:
            self.game.date_end = timezone.now()
            self.game.win = True
            self.game.save()
                
        return super().save(*args, **kwargs)


    class Meta:
        ordering = ['-num']
        default_permissions = ()

mastermind/game/views.py
import json

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import F
from django.db.models.aggregates import Count
from django.db.models.query import prefetch_related_objects
from django.http import HttpResponse
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST

from mastermind.users.decorators import has_perm_game

from .models import Game, Guess


@login_required
def new_game(request, go=None):
    ''' Create a game and start it if go == 'go' '''
    if go == 'go':
        game = Game.objects.create(player=request.user)
        return redirect(game)
    title = _('Ready?')
    return render(request, 'game/ready.html', locals())


@login_required
def game(request, game_id):
    ''' Return the game with remain_rounds so that player can resume a game '''
    game = get_object_or_404(Game, pk=game_id)
    try:
        last_guess = game.guesses.all()[0].num
    except IndexError:
        last_guess = 0
    remain_rounds = range(last_guess + 1, settings.ROUND_NUMBER + 1)
    if game.date_end and game.win:
        title = _('Win!')
    elif game.date_end:
        title = _('Try again!')
    else:
        title = _('Go!')
    return render(request, "game/go.html", locals())


@login_required
@require_POST
@has_perm_game
def guess(request, game_id):
    '''
    AJAX only
    if game belongs to player, return result of guess
    '''
    combination = request.POST['guess']
    game = get_object_or_404(Game, pk=game_id)
    if game.date_end:
        raise IntegrityError
    guess = Guess.objects.create(game=game, combination=combination)
    res = guess.result
    if guess.num == settings.ROUND_NUMBER:
        res['gameover'] = True
    return JsonResponse(res)


@login_required
@has_perm_game
def giveup(request, game_id):
    ''' Giveup current game '''
    game = get_object_or_404(Game, pk=game_id)
    if game.date_end:
        raise IntegrityError
    game.date_end = timezone.now()
    game.save()
    return redirect(game)


@login_required
@require_POST
@has_perm_game
def delete(request, game_id):
    '''
    AJAX Only
    if game belongs to player, player can delete it
    '''
    game = get_object_or_404(Game, pk=game_id)
    game.delete()
    return  HttpResponse(status=200)


@login_required
def ranking(request):
    ''' Display stats of games played by user and other players '''
    games = Game.objects.filter(
        date_end__isnull=False, win=True)\
        .prefetch_related('player', 'guesses') \
        .annotate(num_guesses=Count('guesses'), time=F('date_end') - F('date_begin')) \
        .order_by('num_guesses', 'time')[:100]
    title = _('Ranking')
    return render(request, "game/ranking.html", locals())


@login_required
def user_games(request):
    ''' Display stats of games played by user and other players '''
    games = Game.objects.filter(
        player=request.user)\
        .prefetch_related('player', 'guesses')
    title = _('My games')
    return render(request, "game/user_games.html", locals())

mastermind/game/templates/game/go.html
{% extends "app_base.html" %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load gamefilters %}

{% block addbodyscript %} class="quick" onload="disableColorBlind()"{% endblock addbodyscript %}
{% block addcontentscript %} data-current="0"{% endblock addcontentscript %}

{% block addcss %}
    <link rel="stylesheet" href="{% static 'game/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'game/css/colorblind.css' %}" />
{% endblock addcss %}


{% block addjavascript %}
    <script src="{% static 'game/js/features.js' %}"></script>
    {% if not game.date_end %}
      <script src="{% static 'game/js/clickplace.js' %}"></script>
      <script src="{% static 'game/js/play.js' %}"></script>
      {% include 'game/includes/timer-js.html' %}
    {% endif %}
{% endblock addjavascript %}


{% block content %}

    <div class="row parent">

      {% include 'game/includes/options.html' %}

      <div class="game-container col-md-6 order-md-2">

        <div class="game">

          {% for i in remain_rounds reversed %}
          
            <span class="peg {% if forloop.last and not game.win %}active{% endif %}" data-line="{{ i }}"><i class="gg-close"></i></span>
            <span class="peg {% if forloop.last and not game.win %}active{% endif %}" data-line="{{ i }}"><i class="gg-close"></i></span>
            <span class="peg {% if forloop.last and not game.win %}active{% endif %}" data-line="{{ i }}"><i class="gg-close"></i></span>
            <span class="peg {% if forloop.last and not game.win %}active{% endif %}" data-line="{{ i }}"><i class="gg-close"></i></span>

            <div class="hints {% if forloop.last and not game.win %}active{% endif %}" data-line="{{ i }}">
              <i class="gg-add guess" style="display:none;" data-url="{% url 'game:guess' game.id %}" data-guess="" data-line="{{ i }}"></i>
            </div>
          
          {% endfor %}


          {% for guess in game.guesses.all %}
          
            <span class="peg color{{ guess.color1 }}" data-line="{{ guess.num }}"><i class="gg-close"></i></span>
            <span class="peg color{{ guess.color2 }}" data-line="{{ guess.num }}"><i class="gg-close"></i></span>
            <span class="peg color{{ guess.color3 }}" data-line="{{ guess.num }}"><i class="gg-close"></i></span>
            <span class="peg color{{ guess.color4 }}" data-line="{{ guess.num }}"><i class="gg-close"></i></span>

            <div class="hints" data-line="{{ guess.num }}">
              <i class="gg-add guess" data-url="{% url 'game:guess' game.id %}" data-guess=""></i>
              {% with ''|center:guess.result.good_place as range_good_place %}
                {% for _ in range_good_place %}
                <span class="good_place"></span>
                {% endfor %}
              {% endwith %}
              {% with ''|center:guess.result.wrong_place as range_wrong_place %}
                {% for _ in range_wrong_place %}
                <span class="wrong_place"></span>
                {% endfor %}
              {% endwith %}
            </div>
          
          {% endfor %}
        </div>

        <div class='reserve mb-3'>
          <span class="peg" id="color0" draggable="true"></span>
          <span class="peg" id="color1" draggable="true"></span>
          <span class="peg" id="color2" draggable="true"></span>
          <span class="peg" id="color3" draggable="true"></span>
          <span class="peg" id="color4" draggable="true"></span>
          <span class="peg" id="color5" draggable="true"></span>
        </div>

      </div>


      <div class="col-md-6  order-md-1 text-center text-md-right pb-3 pb-md-0">

        {% if game %}
          <div id="timer">
            <div class="clock-wrapper mx-auto">
              <div class="clock">
                {% if not game.date_end %}
                  <span id="hours">00</span>
                  <span class="dots">:</span>
                  <span id="minutes">00</span>
                  <span class="dots">:</span>
                  <span id="seconds">00</span>
                {% else %}
                  {{ game.duration|duration }}
                {% endif %}
              </div>
            {% if not game.date_end %}
              <a href="{% url 'game:giveup' game.id %}" class="giveup" title="{% translate 'Giveup' %}">
                <span class="fa-stack fa-2x">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fas fa-running fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            {% elif game.date_end and not game.win %}
              <span class="giveup fa-stack fa-2x" title="Failed">
                <i class="fas fa-circle fa-stack-2x text-danger"></i>
                <i class="fas fa-times fa-stack-1x fa-inverse"></i>
              </span>
            {% elif game.date_end and game.win %}
              <span class="giveup fa-stack fa-2x" title="Win">
                <i class="fas fa-circle fa-stack-2x text-success"></i>
                <i class="fas fa-check fa-stack-1x fa-inverse"></i>
              </span>
            {% endif %}
            </div>




          </div>
        
       
        {% else %}
          <h1 class="h3 mb-0 text-gray-800 mr-auto">
              <a href="{% url 'game:new_game' 'go' %}"><i class="far fa-play-circle fa-6x"></i></a>
          </h1>
        {% endif %}
         {% if game.date_end %}
          <div class='solution'>
            <span class="peg color{{ game.peg1 }}"></span>
            <span class="peg color{{ game.peg2 }}"></span>
            <span class="peg color{{ game.peg3 }}"></span>
            <span class="peg color{{ game.peg4 }}"></span>
          </div>
        {% endif %}
      </div>


    </div>

{% endblock content %}

mastermind/game/templates/game/index.html
{% extends "app_base.html" %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

mastermind/game/templates/game/ranking.html
{% extends 'app_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load gamefilters %}

{% block addcss %}
    <link rel="stylesheet" href="{% static 'game/css/style.css' %}" />
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock addcss %}

{% block addjavascript %}
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'game/js/ranking.js' %}"></script>
  <script src="{% url 'javascript-catalog' %}"></script>
{% endblock addjavascript %}

{% block content %}
  <div class="row mb-5">
    <div class="col-xl-7 col-lg-6 mx-auto my-auto">
      <div class="card shadow mb-5">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary"> {% translate "Ranking" %} (top 100)</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="datatable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>{% translate "Rank" %}</th>
                  <th>{% translate "Player" %}</th>
                  <th>{% translate "Solution" %}</th>
                  <th>{% translate "Date" %}</th>
                  <th>{% translate "Guesses" %}</th>
                  <th>{% translate "Time" %}</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th>{% translate "Rank" %}</th>
                  <th>{% translate "Player" %}</th>
                  <th>{% translate "Solution" %}</th>
                  <th>{% translate "Date" %}</th>
                  <th>{% translate "Guesses" %}</th>
                  <th>{% translate "Time" %}</th>
                </tr>
              </tfoot>
              <tbody>
              {% for game in games %}
                <tr>
                  <td>{{ forloop.counter }}
                  {% if forloop.counter == 1 %}<i class="fas fa-award" style="color: #FFD700;"></i>{% endif %}
                  {% if forloop.counter == 2 %}<i class="fas fa-award" style="color: #C0C0C0;"></i>{% endif %}
                  {% if forloop.counter == 3 %}<i class="fas fa-award" style="color: #614e1a;"></i>{% endif %}
                  </td>
                  <td>{{ game.player.username }}</td>
                  <td>
                    <a href="{% url 'game:detail' game.id %}">
                      <div class="solution small">
                        <span class="peg color{{ game.peg1 }}"></span>
                        <span class="peg color{{ game.peg2 }}"></span>
                        <span class="peg color{{ game.peg3 }}"></span>
                        <span class="peg color{{ game.peg4 }}"></span>
                      </div>
                    </a>
                  </td>
                  <td>{{ game.date_begin|date:'SHORT_DATE_FORMAT' }}</td>
                  <td>{{ game.guesses.all.count }}</td>
                  <td>{{ game.duration|duration }}</td>
              {% endfor %}
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div>

  </div>

{% endblock content %}

mastermind/game/templates/game/ready.html
{% extends "app_base.html" %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block addbodyscript %} onload="disableColorBlind()"{% endblock addbodyscript %}

{% block addcss %}
    <link rel="stylesheet" href="{% static 'game/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'game/css/colorblind.css' %}" />
{% endblock addcss %}


{% block addjavascript %}
    <script src="{% static 'game/js/features.js' %}"></script>
{% endblock addjavascript %}


{% block content %}

    <div class="row parent">


      <div class="col-md-6 text-center text-md-right pb-3 pb-md-0">
        <div class="mx-auto">
          <h1 class="h3 mb-0 text-gray-800 mr-auto">
              <a href="{% url 'game:new_game' 'go' %}">
              <img src="{% static 'img/dog-play.png' %}" alt="{% translate 'Click to Play' %}" style="max-width: 60%;">
              <div class="bubble">{% translate 'Click to Play' %}</div>
              </a>
          </h1>
        </div>
      </div>
      <div class="game-container col-md-6">

        <div class="game">
          <span class="peg" data-line="9"></span>
          <span class="peg" data-line="9"></span>
          <span class="peg" data-line="9"></span>
          <span class="peg" data-line="9"></span>
          <div class="hints" data-line="9">
            <i class="gg-add"></i>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
          </div>

          <span class="peg" data-line="8"></span>
          <span class="peg" data-line="8"></span>
          <span class="peg" data-line="8"></span>
          <span class="peg" data-line="8"></span>
          <div class="hints" data-line="8">
            <i class="gg-add"></i>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
          </div>

          <span class="peg" data-line="7"></span>
          <span class="peg" data-line="7"></span>
          <span class="peg" data-line="7"></span>
          <span class="peg" data-line="7"></span>
          <div class="hints" data-line="7">
            <i class="gg-add"></i>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
          </div>

          <span class="peg" data-line="6"></span>
          <span class="peg" data-line="6"></span>
          <span class="peg" data-line="6"></span>
          <span class="peg" data-line="6"></span>
          <div class="hints" data-line="6">
            <i class="gg-add"></i>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
          </div>

          <span class="peg" data-line="5"></span>
          <span class="peg" data-line="5"></span>
          <span class="peg" data-line="5"></span>
          <span class="peg" data-line="5"></span>
          <div class="hints" data-line="5">
            <i class="gg-add"></i>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
          </div>

          <span class="peg" data-line="4"></span>
          <span class="peg" data-line="4"></span>
          <span class="peg" data-line="4"></span>
          <span class="peg" data-line="4"></span>
          <div class="hints" data-line="4">
            <i class="gg-add"></i>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
          </div>

          <span class="peg" data-line="3"></span>
          <span class="peg" data-line="3"></span>
          <span class="peg" data-line="3"></span>
          <span class="peg" data-line="3"></span>
          <div class="hints" data-line="3">
            <i class="gg-add"></i>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
            <span class=""></span>
          </div>

          <span class="peg" data-line="2"><i class="gg-close"></i></span>
          <span class="peg" data-line="2"><i class="gg-close"></i></span>
          <span class="peg" data-line="2"><i class="gg-close"></i></span>
          <span class="peg" data-line="2"><i class="gg-close"></i></span>
          <div class="hints" data-line="2">
            <i class="gg-add"></i>
          </div>

          <span class="peg active" data-line="1"></span>
          <span class="peg active" data-line="1"></span>
          <span class="peg active" data-line="1"></span>
          <span class="peg active" data-line="1"></span>
          <div class="hints active" data-line="1">
            <i class="gg-add"></i>
          </div>
        </div>


      </div>
    </div>

{% endblock content %}

mastermind/game/templates/game/user_games.html
{% extends 'app_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load gamefilters %}

{% block addcss %}
    <link rel="stylesheet" href="{% static 'game/css/style.css' %}" />
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock addcss %}

{% block addjavascript %}
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'game/js/user-games.js' %}"></script>
  <script src="{% url 'javascript-catalog' %}"></script>
{% endblock addjavascript %}

{% block content %}
  <div class="row mb-5">
    <div class="col-xl-7 col-lg-6 mx-auto my-auto">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary"> {% translate "My games" %}</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="datatable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">{% translate 'Win' %}</th>
                  <th>{% translate 'Solution' %}</th>
                  <th>{% translate 'Date' %}</th>
                  <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">{% translate 'Guesses' %}</th>
                  <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">{% translate 'Time' %}</th>
                  <th>{% translate 'Delete' %}</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th>{% translate 'Win' %}</th>
                  <th>{% translate 'Solution' %}</th>
                  <th>{% translate 'Date' %}</th>
                  <th>{% translate 'Guesses' %}</th>
                  <th>{% translate 'Time' %}</th>
                  <th>{% translate 'Delete' %}</th>
                </tr>
              </tfoot>
              <tbody>
              {% for game in games %}
                <tr>
                  <td>
                    {% if not game.date_end %}
                      <span class="fa-stack small">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fas fa-hourglass-half fa-stack-1x fa-inverse"></i>
                      </span>
                    {% elif game.date_end and not game.win %}
                      <span class="fa-stack small" title="Failed">
                        <i class="fas fa-circle fa-stack-2x text-danger"></i>
                        <i class="fas fa-times fa-stack-1x fa-inverse"></i>
                      </span>
                    {% elif game.date_end and game.win %}
                      <span class="fa-stack small" title="Win">
                        <i class="fas fa-circle fa-stack-2x text-success"></i>
                        <i class="fas fa-check fa-stack-1x fa-inverse"></i>
                      </span>
                    {% endif %}
                  
                  </td>
                  <td>
                    <a href="{% url 'game:detail' game.id %}">
                    <div class="solution small">
                      <span class="peg color{{ game.peg1 }}"></span>
                      <span class="peg color{{ game.peg2 }}"></span>
                      <span class="peg color{{ game.peg3 }}"></span>
                      <span class="peg color{{ game.peg4 }}"></span>
                    </div>
                    </a>
                  </td>
                  <td data-sort="{{ game.date_begin|date:'%Y-%m-%d' }}">{{ game.date_begin|date:'SHORT_DATE_FORMAT' }}</td>
                  <td>{{ game.guesses.all.count }}</td>
                  <td>
                    {{ game.duration|duration }}
                  </td>
                  <td>
                    <i class="fas fa-trash-alt text-danger remove" data-url="{% url 'game:delete' game.id %}"></i>
                  </td>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>

{% endblock content %}