mastermind/game/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from mastermind.game import views

app_name = 'game'

urlpatterns = [
    path("", TemplateView.as_view(template_name='game/index.html'), name="index"),
    path("<int:game_id>/", views.game, name="detail"),
    path("<int:game_id>/giveup/", views.giveup, name="giveup"),
    path("new/", views.new_game, name="new_game"),
    path("ranking/", views.ranking, name="ranking"),
    path("my-games/", views.user_games, name="user_games"),
    path("new/<str:go>/", views.new_game, name="new_game"),
    path("<int:game_id>/guess/", views.guess, name="guess"),
    path("<int:game_id>/delete/", views.delete, name="delete"),
]

mastermind/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog

urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),] + (
    i18n_patterns(
        path('', include('mastermind.users.urls', namespace="users")),
        path('game/', include('mastermind.game.urls', namespace="game")),
        path("rules/", TemplateView.as_view(template_name='pages/rules.html'), name="rules"),
        path("terms/", TemplateView.as_view(template_name='pages/terms.html'), name="terms"),
        path('admin/', admin.site.urls),
        path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
        prefix_default_language=True
    ) 
)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += [
    #     path(
    #         "400/",
    #         default_views.bad_request,
    #         kwargs={"exception": Exception("Bad Request!")},
    #     ),
    #     path(
    #         "403/",
    #         default_views.permission_denied,
    #         kwargs={"exception": Exception("Permission Denied")},
    #     ),
    #     path(
    #         "404/",
    #         default_views.page_not_found,
    #         kwargs={"exception": Exception("Page not Found")},
    #     ),
    #     path("500/", default_views.server_error),
    # ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mastermind/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from mastermind.users import views

app_name = 'users'

urlpatterns = [
    path("", views.login_view, name="index"),
    path('signup/', views.signup_view, name='signup'),
    path('account/', views.account, name='account'),
    path('delete-account/', views.delete_account, name='delete_account'),
    path("signup/<uuid:token>/", views.signup_view, name="signup"),
    path('activate/<uidb64>/<token>/', views.activate_user, name='activate'),
    # django.contrib.auth views
    path('signin/', views.login_view, name='signin'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="users/registration/password_reset_done.html"), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="users/registration/password_reset_complete.html"), name='password_reset_complete'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app_base.html
<!DOCTYPE html>{% load crispy_forms_tags static i18n %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="">
  <title>{% block title %}{% if title %}{{ title }}{% endif %}{% endblock %} - Mastermind</title>
  <meta name="description" content="{% block meta-description %}{% endblock %}">


  <!-- Custom styles for this template-->
  {% block addcss %}{% endblock addcss %}
  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="{% static 'css/app.min.css' %}" rel="stylesheet">


</head>

<body id="page-top" {% block addbodyscript %}{% endblock addbodyscript %}>

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark toggled" id="accordionSidebar">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item {% if 'new_game' in request.resolver_match.url_name %}active {% endif %}">
        <a class="nav-link" href="{% url 'game:new_game' %}">
          <i class="fas fa-fw fa-gamepad"></i>
          <span>{% translate 'Play' %}</span></a>
      </li>

      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'game:ranking' %}">
          <i class="fas fa-fw fa-award"></i>
          <span>{% translate 'Ranking' %}</span></a>
      </li>


      <!-- Nav Item - Language -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#language" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-language fa-fw"></i>
          <span>{% translate 'Language' %}</span>
        </a>
        <div id="language" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">


              <form id="spanish" action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input name="language" type="hidden" value="es"></input>
                <input name="next" type="hidden" value="{{ urlpath }}">
              </form>
              <a class="collapse-item"  href="javascript:;" onclick="document.getElementById('spanish').submit();">
                <img src="{% static 'img/flag/spain.png' %}" alt="Spanish" class="fas fa-cog fa-sm fa-fw mr-2 text-gray-400">
                {% translate 'Spanish' %}
              </a>


              <form id="french" action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input name="language" type="hidden" value="fr"></input>
                <input name="next" type="hidden" value="{{ urlpath }}">
              </form>
              <a class="collapse-item"  href="javascript:;" onclick="document.getElementById('french').submit();">
                <img src="{% static 'img/flag/france.png' %}" alt="French" class="fas fa-cog fa-sm fa-fw mr-2 text-gray-400">
                {% translate 'French' %}
              </a>


              <form id="english" action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input name="language" type="hidden" value="en"></input>
                <input name="next" type="hidden" value="{{ urlpath }}">
              </form>
              <a class="collapse-item"  href="javascript:;" onclick="document.getElementById('english').submit();">
                <img src="{% static 'img/flag/united-states-of-america.png' %}" alt="English" class="fas fa-cog fa-sm fa-fw mr-2 text-gray-400">
                {% translate 'English' %}
              </a>

          </div>
        </div>
      </li>

      <!-- Nav Item - Profile -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Profile" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-user fa-fw"></i>
          <span>{% translate 'Profile' %}</span>
        </a>
        <div id="Profile" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'users:account' %}">
              <i class="fas fa-cog fa-sm fa-fw mr-2 text-gray-400"></i>
              {% translate 'Settings' %}
            </a>
            <a class="collapse-item" href="{% url 'game:user_games' %}">
              <i class="fas fa-chart-bar fa-sm fa-fw mr-2 text-gray-400"></i>
              {% translate 'My games' %}
            </a>
            <a class="collapse-item" href="#"  data-toggle="modal" data-target="#logoutModal">
              <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
              {% translate 'Logout' %} 
            </a>
          </div>
        </div>
      </li>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content" {% block addcontentscript %}{% endblock addcontentscript %}>

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <div class="row">
          <div class="col-xl-7 col-lg-6 mx-auto my-auto">
          {% if messages %}
            {% for message in messages %}
              <div class="card py-3 alert alert-dismissible fade show {% if message.tags %}border-bottom-{{ message.tags }}{% endif %}" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
          {% endif %}
          </div>
          </div>


          <!-- Content Row -->
          {% block content %}{% endblock content %}

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{% translate 'Ready to Leave?' %}</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">{% translate 'Select "Logout" below if you are ready to end your current session.' %}</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">{% translate 'Cancel' %}</button>
          <a class="btn btn-primary" href="{% url 'users:logout' %}">{% translate 'Logout' %}</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/app.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  {% block addjavascript %}{% endblock addjavascript %}

</body>

</html>

templates/site_base.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
{% load i18n urls %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <meta name="author" content="">
  <title>{% block title %}{% if title %}{{ title }}{% endif %}{% endblock %} - Mastermind</title>
  <meta name="description" content="{% block meta-description %}{% endblock %}">

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/app.min.css' %}" rel="stylesheet">

  {% get_available_languages as LANGUAGES %}
  {% for language_code, language_name in LANGUAGES %}
  <link
      rel="alternate"
      hreflang="{{ language_code }}"
      href="{% translate_url language_code %}" />
  {% endfor %}
  <link
      rel="alternate"
      hreflang="x-default"
    href="{% translate_url en %}" />

</head>

<body class="bg-gradient-primary">

  <div class="container">

    {% if messages %}
      {% for message in messages %}
        <div class="card py-3 alert alert-dismissible fade show {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}

    {% block content %}
    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">{% block h1 %}Welcome Back!{% endblock h1 %}</h1>
                  </div>
                  <form class="user">
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                    <a href="index.html" class="btn btn-primary btn-user btn-block">
                      Login
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        

      </div>

    </div>
    {% endblock content %}

    <div class=" text-center">
      <div class="d-inline-flex">

        <form id="spanish" action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input name="language" type="hidden" value="es"></input>
          <input name="next" type="hidden" value="{{ urlpath }}">
        </form>
        <a class="collapse-item"  href="javascript:;" onclick="document.getElementById('spanish').submit();">
          <img src="{% static 'img/flag/spain.png' %}" alt="Spanish" class="flag">
        </a>


        <form id="french" action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input name="language" type="hidden" value="fr"></input>
          <input name="next" type="hidden" value="{{ urlpath }}">
        </form>
        <a class="collapse-item"  href="javascript:;" onclick="document.getElementById('french').submit();">
          <img src="{% static 'img/flag/france.png' %}" alt="French" class="flag">
        </a>


        <form id="english" action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input name="language" type="hidden" value="en"></input>
          <input name="next" type="hidden" value="{{ urlpath }}">
        </form>
        <a class="collapse-item"  href="javascript:;" onclick="document.getElementById('english').submit();">
          <img src="{% static 'img/flag/united-states-of-america.png' %}" alt="French" class="flag">
        </a>
      </div>
    </div>

{% if rules %}
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-4">
            {% include "pages/rules.html" %}
          </div>
        </div>
      </div>
    </div>

  {% endif %}


  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/app.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
  <script>
  $(document).ready(function(){
    $('.toast').toast('show');
  });
  </script>

</body>

</html>